/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BUSUI;

import BUSDOMAIN.*;
import BUSCONTROL.*;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author sooxl
 */
public class StaffForgetPassword extends javax.swing.JFrame {

    private int count = 0;
    private Staff stf;
    private MaintainStaffControl staffControl = new MaintainStaffControl();
    private boolean checkUser = false;

    public StaffForgetPassword() {
        initComponents();
        jbtCheckSQ.setVisible(false);
        resetPanel.setVisible(false);
        setTitle("Forget Password");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        resetPanel = new javax.swing.JPanel();
        jlbStaffName = new javax.swing.JLabel();
        jlbHi = new javax.swing.JLabel();
        jbtResetPW = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jlbCurrentSQ = new javax.swing.JLabel();
        jbtCheckSQ = new javax.swing.JButton();
        jtfCurrentSP = new javax.swing.JTextField();
        jlbCurrentSP = new javax.swing.JLabel();
        jlbCurrentUsername = new javax.swing.JLabel();
        jtfCurrentUsername = new javax.swing.JTextField();
        jbtCheckUser = new javax.swing.JButton();
        jtfCurrentSQ = new javax.swing.JTextField();
        jlbHome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        resetPanel.setBackground(new java.awt.Color(255, 255, 255));
        resetPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reset Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 24), new java.awt.Color(0, 153, 153))); // NOI18N

        jlbStaffName.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jlbStaffName.setForeground(new java.awt.Color(204, 0, 204));

        jlbHi.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jlbHi.setForeground(new java.awt.Color(204, 0, 204));
        jlbHi.setText("Hi, ");

        jbtResetPW.setBackground(new java.awt.Color(192, 57, 43));
        jbtResetPW.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jbtResetPW.setForeground(new java.awt.Color(255, 255, 255));
        jbtResetPW.setText("Reset Password to Default");
        jbtResetPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtResetPWActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(204, 51, 0));
        jLabel1.setText("*Default Password : 12345678");

        javax.swing.GroupLayout resetPanelLayout = new javax.swing.GroupLayout(resetPanel);
        resetPanel.setLayout(resetPanelLayout);
        resetPanelLayout.setHorizontalGroup(
            resetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resetPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jlbHi)
                .addGap(18, 18, 18)
                .addComponent(jlbStaffName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
            .addGroup(resetPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(resetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jbtResetPW, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        resetPanelLayout.setVerticalGroup(
            resetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resetPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbStaffName, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbHi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jbtResetPW, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Forget Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 24), new java.awt.Color(0, 102, 102))); // NOI18N

        jlbCurrentSQ.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jlbCurrentSQ.setText("Current Security Question:");

        jbtCheckSQ.setBackground(new java.awt.Color(192, 57, 43));
        jbtCheckSQ.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jbtCheckSQ.setForeground(new java.awt.Color(255, 255, 255));
        jbtCheckSQ.setText("Check Security Password");
        jbtCheckSQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCheckSQActionPerformed(evt);
            }
        });

        jtfCurrentSP.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jtfCurrentSP.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfCurrentSP.setEnabled(false);
        jtfCurrentSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCurrentSPActionPerformed(evt);
            }
        });

        jlbCurrentSP.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jlbCurrentSP.setText("Current Security Password:");

        jlbCurrentUsername.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jlbCurrentUsername.setText("Current Username:");

        jtfCurrentUsername.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        jbtCheckUser.setText("Check Username");
        jbtCheckUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCheckUserActionPerformed(evt);
            }
        });

        jtfCurrentSQ.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jtfCurrentSQ.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfCurrentSQ.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbCurrentUsername)
                    .addComponent(jlbCurrentSP)
                    .addComponent(jlbCurrentSQ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfCurrentSP, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jtfCurrentUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtCheckUser, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtfCurrentSQ, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtCheckSQ, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCurrentUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCurrentUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtCheckUser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCurrentSQ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCurrentSQ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCurrentSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbCurrentSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtCheckSQ)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlbHome.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jlbHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xlImages/home.png"))); // NOI18N
        jlbHome.setText("Back to Login");
        jlbHome.setToolTipText("Home");
        jlbHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbHomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(425, 425, 425)
                        .addComponent(resetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jlbHome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(575, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jlbHome, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addComponent(resetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtResetPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtResetPWActionPerformed
        stf.setPassword("12345678");
        staffControl.updateRecord(stf);
        JOptionPane.showMessageDialog(null, "Your Password has change to 12345678. Please change it in your next login in the P & C info.", "Reset Password Successfully", JOptionPane.INFORMATION_MESSAGE);
        dispose();
    }//GEN-LAST:event_jbtResetPWActionPerformed

    private void jbtCheckSQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCheckSQActionPerformed
        if (jtfCurrentSP.getText().equals(stf.getSecuritypass())) {
            resetPanel.setVisible(true);
            jlbStaffName.setText(stf.getStaffname());
            JOptionPane.showMessageDialog(null, "Click on Reset Button to rest your password to 12345678.", "Reset Password", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Invalid Security Answer ", "Wrong Answer", JOptionPane.ERROR_MESSAGE);
            jtfCurrentSP.setText("");
            closeProgram();
        }

    }//GEN-LAST:event_jbtCheckSQActionPerformed

    private void jbtCheckUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCheckUserActionPerformed
        String id = jtfCurrentUsername.getText();
        stf = staffControl.selectRecordbyUsername(id);
        if (stf != null) {

            jtfCurrentSQ.setText(stf.getSecurityquestion());
            jtfCurrentUsername.setEnabled(false);
            checkUser = true;
            count = 0;
            jbtCheckUser.setVisible(false);
            jtfCurrentSP.setEnabled(true);
            jbtCheckSQ.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Invalid user ID ", "STAFF NOT FOUND", JOptionPane.ERROR_MESSAGE);
            jtfCurrentUsername.setText("");
            closeProgram();
        }
    }//GEN-LAST:event_jbtCheckUserActionPerformed

    private void jtfCurrentSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCurrentSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCurrentSPActionPerformed

    private void jlbHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbHomeMouseClicked

        dispose();
    }//GEN-LAST:event_jlbHomeMouseClicked

    public void closeProgram() {

        count++;
        if (count == 3) {
            JOptionPane.showMessageDialog(null, "You've typed the invalid username or wrong answer for 3 times!!!", "Closing Program...", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffForgetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtCheckSQ;
    private javax.swing.JButton jbtCheckUser;
    private javax.swing.JButton jbtResetPW;
    private javax.swing.JLabel jlbCurrentSP;
    private javax.swing.JLabel jlbCurrentSQ;
    private javax.swing.JLabel jlbCurrentUsername;
    private javax.swing.JLabel jlbHi;
    private javax.swing.JLabel jlbHome;
    private javax.swing.JLabel jlbStaffName;
    private javax.swing.JTextField jtfCurrentSP;
    private javax.swing.JTextField jtfCurrentSQ;
    private javax.swing.JTextField jtfCurrentUsername;
    private javax.swing.JPanel resetPanel;
    // End of variables declaration//GEN-END:variables
}
